# Generated by Django 4.0.5 on 2022-09-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_UserProfile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_varified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='otp',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
