# Generated by Django 4.0.5 on 2022-09-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_shop', '0003_alter_product_is_active_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_img',
            field=models.ImageField(blank=True, null=True, upload_to='shop/image/category/'),
        ),
    ]
