# Generated by Django 4.0.5 on 2022-09-13 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_shop', '0005_blogcategory_articel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articel',
            name='slug',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
