# Generated by Django 4.0.5 on 2022-09-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_shop', '0006_alter_articel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articel',
            name='slug',
            field=models.SlugField(max_length=80, unique=True),
        ),
    ]
